package com.productcatalog.datamodel;
// Generated Sep 19, 2018 12:55:43 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productlines generated by hbm2java
 */
@Entity
@Table(name = "productlines")
public class Productlines implements java.io.Serializable {

	private String productLine;
	private String textDescription;
	private String htmlDescription;
	private byte[] image;
	private Set<Products> productses = new HashSet<Products>(0);

	public Productlines() {
	}

	public Productlines(String productLine) {
		this.productLine = productLine;
	}

	public Productlines(String productLine, String textDescription, String htmlDescription, byte[] image,
			Set<Products> productses) {
		this.productLine = productLine;
		this.textDescription = textDescription;
		this.htmlDescription = htmlDescription;
		this.image = image;
		this.productses = productses;
	}

	@Id

	@Column(name = "productLine", unique = true, nullable = false, length = 50)
	public String getProductLine() {
		return this.productLine;
	}

	public void setProductLine(String productLine) {
		this.productLine = productLine;
	}

	@Column(name = "textDescription", length = 4000)
	public String getTextDescription() {
		return this.textDescription;
	}

	public void setTextDescription(String textDescription) {
		this.textDescription = textDescription;
	}

	@Column(name = "htmlDescription", length = 16777215)
	public String getHtmlDescription() {
		return this.htmlDescription;
	}

	public void setHtmlDescription(String htmlDescription) {
		this.htmlDescription = htmlDescription;
	}

	@Column(name = "image")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productlines")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
